-- Migration to add missing fields from school master application format
ALTER TABLE public.applications
ADD COLUMN IF NOT EXISTS preferred_language TEXT,
ADD COLUMN IF NOT EXISTS is_boarder BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS citizenship TEXT,
ADD COLUMN IF NOT EXISTS deceased_parent TEXT,
ADD COLUMN IF NOT EXISTS religion TEXT,
ADD COLUMN IF NOT EXISTS mode_of_transport TEXT,
ADD COLUMN IF NOT EXISTS current_school_address TEXT,
ADD COLUMN IF NOT EXISTS medical_aid_name TEXT,
ADD COLUMN IF NOT EXISTS medical_aid_number TEXT,
ADD COLUMN IF NOT EXISTS medical_main_member TEXT,
ADD COLUMN IF NOT EXISTS doctor_name TEXT,
ADD COLUMN IF NOT EXISTS doctor_contact TEXT,
ADD COLUMN IF NOT EXISTS medical_condition TEXT,
ADD COLUMN IF NOT EXISTS special_problems TEXT,
ADD COLUMN IF NOT EXISTS dexterity TEXT,
ADD COLUMN IF NOT EXISTS siblings_info TEXT,
ADD COLUMN IF NOT EXISTS parent_primary_title TEXT,
ADD COLUMN IF NOT EXISTS parent_primary_surname TEXT,
ADD COLUMN IF NOT EXISTS parent_primary_gender TEXT,
ADD COLUMN IF NOT EXISTS parent_primary_occupation TEXT,
ADD COLUMN IF NOT EXISTS parent_primary_employer TEXT,
ADD COLUMN IF NOT EXISTS parent_primary_marital_status TEXT,
ADD COLUMN IF NOT EXISTS parent_secondary_title TEXT,
ADD COLUMN IF NOT EXISTS parent_secondary_surname TEXT,
ADD COLUMN IF NOT EXISTS parent_secondary_gender TEXT,
ADD COLUMN IF NOT EXISTS parent_secondary_occupation TEXT,
ADD COLUMN IF NOT EXISTS parent_secondary_employer TEXT,
ADD COLUMN IF NOT EXISTS parent_secondary_id_number TEXT,
ADD COLUMN IF NOT EXISTS parent_secondary_address TEXT,
ADD COLUMN IF NOT EXISTS parent_secondary_marital_status TEXT,
ADD COLUMN IF NOT EXISTS parent_secondary_relationship TEXT;
